Reference: https://www.cdc.gov/brfss/annual_data/2015/pdf/codebook15_llcp.pdf

In [1]:
import pandas as pd

In [2]:
PREFIX_PATH = '../../data/raw'

In [3]:
genhlth_df = pd.DataFrame([
    {"value": 1, "label": "Excellent"},
    {"value": 2, "label": "Very Good"},
    {"value": 3, "label": "Good"},
    {"value": 4, "label": "Fair"},
    {"value": 5, "label": "Poor"}
])
genhlth_df.to_csv(f"{PREFIX_PATH}/genhlth.csv", index=False)
genhlth_df

   value      label
0      1  Excellent
1      2  Very Good
2      3       Good
3      4       Fair
4      5       Poor

In [4]:
x_ageg5yr_df = pd.DataFrame([
    {"value": 1, "label": "18 to 24"},
    {"value": 2, "label": "25 to 29"},
    {"value": 3, "label": "30 to 34"},
    {"value": 4, "label": "35 to 39"},
    {"value": 5, "label": "40 to 44"},
    {"value": 6, "label": "45 to 49"},
    {"value": 7, "label": "50 to 54"},
    {"value": 8, "label": "55 to 59"},
    {"value": 9, "label": "60 to 64"},
    {"value": 10, "label": "65 to 69"},
    {"value": 11, "label": "70 to 74"},
    {"value": 12, "label": "75 to 79"},
    {"value": 13, "label": "80 or older"},
    {"value": 14, "label": "Don't know/Refused/Missing"},
])
x_ageg5yr_df.to_csv(f"{PREFIX_PATH}/x_ageg5yr.csv", index=False)
x_ageg5yr_df

    value                       label
0       1                    18 to 24
1       2                    25 to 29
2       3                    30 to 34
3       4                    35 to 39
4       5                    40 to 44
5       6                    45 to 49
6       7                    50 to 54
7       8                    55 to 59
8       9                    60 to 64
9      10                    65 to 69
10     11                    70 to 74
11     12                    75 to 79
12     13                 80 or older
13     14  Don't know/Refused/Missing

In [5]:
x_bmi5cat_df = pd.DataFrame([
    {"value": 1, "label": "Underweight"},
    {"value": 2, "label": "Normal weight"},
    {"value": 3, "label": "Overweight"},
    {"value": 4, "label": "Obese"},
])
x_bmi5cat_df.to_csv(f"{PREFIX_PATH}/x_bmi5cat.csv", index=False)
x_bmi5cat_df

   value          label
0      1    Underweight
1      2  Normal weight
2      3     Overweight
3      4          Obese

In [6]:
income2_df = pd.DataFrame(
    [
        {"value": 1, "label": "Less than $10,000"},
        {"value": 2, "label": "$10,000 to $15,000"},
        {"value": 3, "label": "$15,000 to $20,000"},
        {"value": 4, "label": "$20,000 to $25,000"},
        {"value": 5, "label": "$25,000 to $35,000"},
        {"value": 6, "label": "$35,000 to $50,000"},
        {"value": 7, "label": "$50,000 to $75,000"},
        {"value": 8, "label": "Over $75,000"},
    ]
)
income2_df.to_csv(f"{PREFIX_PATH}/income2.csv", index=False)
income2_df

   value               label
0      1   Less than $10,000
1      2  $10,000 to $15,000
2      3  $15,000 to $20,000
3      4  $20,000 to $25,000
4      5  $25,000 to $35,000
5      6  $35,000 to $50,000
6      7  $50,000 to $75,000
7      8        Over $75,000

In [7]:
sex_df = pd.DataFrame([
    {"value": 1, "label": "Male"},
    {"value": 2, "label": "Female"}
])
sex_df.to_csv(f"{PREFIX_PATH}/sex.csv", index=False)
sex_df

   value   label
0      1    Male
1      2  Female

In [8]:
state_df = pd.DataFrame([
    {"StateId": 1, "StateName": "Alabama"},
    {"StateId": 2, "StateName": "Alaska"},
    {"StateId": 4, "StateName": "Arizona"},
    {"StateId": 5, "StateName": "Arkansas"},      
    {"StateId": 6, "StateName": "California"},
    {"StateId": 8, "StateName": "Colorado"},
    {"StateId": 9, "StateName": "Connecticut"},
    {"StateId": 10, "StateName": "Delaware"},
    {"StateId": 11, "StateName": "District of Columbia"},
    {"StateId": 12, "StateName": "Florida"},
    {"StateId": 13, "StateName": "Georgia"},
    {"StateId": 15, "StateName": "Hawaii"},
    {"StateId": 16, "StateName": "Idaho"},
    {"StateId": 17, "StateName": "Illinois"},
    {"StateId": 18, "StateName": "Indiana"},
    {"StateId": 19, "StateName": "Iowa"},
    {"StateId": 20, "StateName": "Kansas"},
    {"StateId": 21, "StateName": "Kentucky"},
    {"StateId": 22, "StateName": "Louisiana"},
    {"StateId": 23, "StateName": "Maine"},
    {"StateId": 24, "StateName": "Maryland"},
    {"StateId": 25, "StateName": "Massachusetts"},
    {"StateId": 26, "StateName": "Michigan"},
    {"StateId": 27, "StateName": "Minnesota"},
    {"StateId": 28, "StateName": "Mississippi"},
    {"StateId": 29, "StateName": "Missouri"},
    {"StateId": 30, "StateName": "Montana"},
    {"StateId": 31, "StateName": "Nebraska"},
    {"StateId": 32, "StateName": "Nevada"},
    {"StateId": 33, "StateName": "New Hampshire"},
    {"StateId": 34, "StateName": "New Jersey"},
    {"StateId": 35, "StateName": "New Mexico"},
    {"StateId": 36, "StateName": "New York"},
    {"StateId": 37, "StateName": "North Carolina"},
    {"StateId": 38, "StateName": "North Dakota"},
    {"StateId": 39, "StateName": "Ohio"},
    {"StateId": 40, "StateName": "Oklahoma"},
    {"StateId": 41, "StateName": "Oregon"},
    {"StateId": 42, "StateName": "Pennsylvania"},
    {"StateId": 44, "StateName": "Rhode Island"},
    {"StateId": 45, "StateName": "South Carolina"},
    {"StateId": 46, "StateName": "South Dakota"},
    {"StateId": 47, "StateName": "Tennessee"},
    {"StateId": 48, "StateName": "Texas"},
    {"StateId": 49, "StateName": "Utah"},
    {"StateId": 50, "StateName": "Vermont"},
    {"StateId": 51, "StateName": "Virginia"},
    {"StateId": 53, "StateName": "Washington"},
    {"StateId": 54, "StateName": "West Virginia"},
    {"StateId": 55, "StateName": "Wisconsin"},
    {"StateId": 56, "StateName": "Wyoming"},
    {"StateId": 66, "StateName": "Guam"},
    {"StateId": 72, "StateName": "Puerto Rico"}
])
state_df.to_csv(f"{PREFIX_PATH}/state.csv", index=False)